# Set the following environment variables before running `docker-compose up -d` command
#
# SHORT_URL_MYSQL_USER=short-url
# SHORT_URL_MYSQL_PASSWORD=short-url-password
# SHORT_URL_MYSQL_ROOT_PASSWORD=root-password
# SHORT_URL_MYSQL_DATABASE=short-url
# SHORT_URL_MYSQL_HOST_PORT=33060
# SHORT_URL_NETWORK_SUBNET=192.168.222

version: '3.6'

networks:
    short-url-network:
        name: short-url-network
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: "${SHORT_URL_NETWORK_SUBNET:-192.168.222}.0/28"

volumes:
    short-url-mysql-data:
        name: short-url-mysql-data
        driver: local

services:
    short-url-mysql:
        build:
            args:
                APPLICATION_PATH: /var/www/short-url
                MYSQL_USER: ${SHORT_URL_MYSQL_USER:-short-url}
                MYSQL_PASSWORD: ${SHORT_URL_MYSQL_PASSWORD:-short-url-password}
                MYSQL_ROOT_PASSWORD: ${SHORT_URL_MYSQL_ROOT_PASSWORD:-root-password}
                MYSQL_DATABASE: ${SHORT_URL_MYSQL_DATABASE:-short-url}
            context: ./
            dockerfile: build/mysql/Dockerfile
        container_name: short-url-mysql
        networks:
            short-url-network:
                ipv4_address: "${SHORT_URL_NETWORK_SUBNET:-192.168.222}.2"
        ports:
            - "${SHORT_URL_MYSQL_HOST_PORT:-33060}:3306"
        restart: "no"
        tty: true
#        healthcheck:
#            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
#            timeout: 30s
#            retries: 10
        volumes:
            - ./:/var/www/short-url/
            - short-url-mysql-data:/var/lib/mysql/
            - ./var/log/mysql/:/var/log/mysql/

    short-url-php-fpm:
        build:
            args:
                APP_ENV: devlocal
                APPLICATION_PATH: /var/www/short-url
                MYSQL_USER: ${SHORT_URL_MYSQL_USER:-short-url}
                MYSQL_PASSWORD: ${SHORT_URL_MYSQL_PASSWORD:-short-url-password}
                MYSQL_ROOT_PASSWORD: ${SHORT_URL_MYSQL_ROOT_PASSWORD:-root-password}
                MYSQL_DATABASE: ${SHORT_URL_MYSQL_DATABASE:-short-url}
                NETWORK_SUBNET: ${SHORT_URL_NETWORK_SUBNET:-192.168.222}
            context: ./
            dockerfile: build/php-fpm/Dockerfile
        container_name: short-url-php-fpm
        links:
            - short-url-mysql
        depends_on:
            - short-url-mysql
        ports:
            - "9000:9000"
        expose:
            - 9000
        networks:
            short-url-network:
                ipv4_address: "${SHORT_URL_NETWORK_SUBNET:-192.168.222}.3"
        restart: always
        tty: true
        volumes:
            - ./:/var/www/short-url/
            - ./var/log/php-fpm/:/var/log/php-fpm/
