# Set the following environment variables before running `docker-compose up -d` command
#
# CACHE_TEST_MYSQL_USER=cache-test
# CACHE_TEST_MYSQL_PASSWORD=cache-test-password
# CACHE_TEST_MYSQL_ROOT_PASSWORD=root-password
# CACHE_TEST_MYSQL_DATABASE=cache-test
# CACHE_TEST_MYSQL_HOST_PORT=33060
# CACHE_TEST_NETWORK_SUBNET=192.168.222

version: '3.6'

networks:
    cache-test-network:
        name: cache-test-network
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: "${CACHE_TEST_NETWORK_SUBNET:-192.168.222}.0/28"

volumes:
    cache-test-mysql-data:
        name: cache-test-mysql-data
        driver: local

services:
    cache-test-mysql:
        build:
            args:
                APPLICATION_PATH: /var/www/cache-test
                MYSQL_USER: ${CACHE_TEST_MYSQL_USER:-cache-test}
                MYSQL_PASSWORD: ${CACHE_TEST_MYSQL_PASSWORD:-cache-test-password}
                MYSQL_ROOT_PASSWORD: ${CACHE_TEST_MYSQL_ROOT_PASSWORD:-root-password}
                MYSQL_DATABASE: ${CACHE_TEST_MYSQL_DATABASE:-cache-test}
            context: ./
            dockerfile: build/mysql/Dockerfile
        container_name: cache-test-mysql
        networks:
            cache-test-network:
                ipv4_address: "${CACHE_TEST_NETWORK_SUBNET:-192.168.222}.2"
        ports:
            - "${CACHE_TEST_MYSQL_HOST_PORT:-33060}:3306"
        restart: "no"
        tty: true
#        healthcheck:
#            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
#            timeout: 30s
#            retries: 10
        volumes:
            - ./:/var/www/cache-test/
            - cache-test-mysql-data:/var/lib/mysql/
            - ./var/log/mysql/:/var/log/mysql/

    cache-test-php-fpm:
        build:
            args:
                APP_ENV: devlocal
                APPLICATION_PATH: /var/www/cache-test
                MYSQL_USER: ${CACHE_TEST_MYSQL_USER:-cache-test}
                MYSQL_PASSWORD: ${CACHE_TEST_MYSQL_PASSWORD:-cache-test-password}
                MYSQL_ROOT_PASSWORD: ${CACHE_TEST_MYSQL_ROOT_PASSWORD:-root-password}
                MYSQL_DATABASE: ${CACHE_TEST_MYSQL_DATABASE:-cache-test}
                NETWORK_SUBNET: ${CACHE_TEST_NETWORK_SUBNET:-192.168.222}
            context: ./
            dockerfile: build/php-fpm/Dockerfile
        container_name: cache-test-php-fpm
        links:
            - cache-test-mysql
        depends_on:
            - cache-test-mysql
        ports:
            - "9000:9000"
        expose:
            - 9000
        networks:
            cache-test-network:
                ipv4_address: "${CACHE_TEST_NETWORK_SUBNET:-192.168.222}.3"
        restart: always
        tty: true
        volumes:
            - ./:/var/www/cache-test/
            - ./var/log/php-fpm/:/var/log/php-fpm/
